"""initial schema

Revision ID: d432371fb104
Revises: 
Create Date: 2026-03-20 14:57:30.819851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd432371fb104'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('employee_no', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=False),
    sa.Column('job_family', sa.String(length=128), nullable=False),
    sa.Column('job_level', sa.String(length=64), nullable=False),
    sa.Column('manager_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], name=op.f('fk_employees_manager_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees'))
    )
    op.create_index(op.f('ix_employees_department'), 'employees', ['department'], unique=False)
    op.create_index(op.f('ix_employees_employee_no'), 'employees', ['employee_no'], unique=True)
    op.create_index(op.f('ix_employees_job_family'), 'employees', ['job_family'], unique=False)
    op.create_index(op.f('ix_employees_job_level'), 'employees', ['job_level'], unique=False)
    op.create_index(op.f('ix_employees_manager_id'), 'employees', ['manager_id'], unique=False)
    op.create_index(op.f('ix_employees_name'), 'employees', ['name'], unique=False)
    op.create_index(op.f('ix_employees_status'), 'employees', ['status'], unique=False)
    op.create_table('evaluation_cycles',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('review_period', sa.String(length=128), nullable=False),
    sa.Column('budget_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_cycles'))
    )
    op.create_index(op.f('ix_evaluation_cycles_name'), 'evaluation_cycles', ['name'], unique=False)
    op.create_index(op.f('ix_evaluation_cycles_status'), 'evaluation_cycles', ['status'], unique=False)
    op.create_table('import_jobs',
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('import_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('success_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('result_summary', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_jobs'))
    )
    op.create_index(op.f('ix_import_jobs_import_type'), 'import_jobs', ['import_type'], unique=False)
    op.create_index(op.f('ix_import_jobs_status'), 'import_jobs', ['status'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('operator_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], name=op.f('fk_audit_logs_operator_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_operator_id'), 'audit_logs', ['operator_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_id'), 'audit_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_type'), 'audit_logs', ['target_type'], unique=False)
    op.create_table('certifications',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('certification_type', sa.String(length=64), nullable=False),
    sa.Column('certification_stage', sa.String(length=64), nullable=False),
    sa.Column('bonus_rate', sa.Float(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_certifications_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certifications'))
    )
    op.create_index(op.f('ix_certifications_certification_stage'), 'certifications', ['certification_stage'], unique=False)
    op.create_index(op.f('ix_certifications_employee_id'), 'certifications', ['employee_id'], unique=False)
    op.create_table('employee_submissions',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('cycle_id', sa.String(length=36), nullable=False),
    sa.Column('self_summary', sa.Text(), nullable=True),
    sa.Column('manager_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['evaluation_cycles.id'], name=op.f('fk_employee_submissions_cycle_id_evaluation_cycles')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_submissions_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_submissions')),
    sa.UniqueConstraint('employee_id', 'cycle_id', name=op.f('uq_employee_submissions_employee_id'))
    )
    op.create_index(op.f('ix_employee_submissions_cycle_id'), 'employee_submissions', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_employee_submissions_employee_id'), 'employee_submissions', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_submissions_status'), 'employee_submissions', ['status'], unique=False)
    op.create_table('ai_evaluations',
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('ai_level', sa.String(length=32), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['employee_submissions.id'], name=op.f('fk_ai_evaluations_submission_id_employee_submissions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_evaluations'))
    )
    op.create_index(op.f('ix_ai_evaluations_ai_level'), 'ai_evaluations', ['ai_level'], unique=False)
    op.create_index(op.f('ix_ai_evaluations_status'), 'ai_evaluations', ['status'], unique=False)
    op.create_index(op.f('ix_ai_evaluations_submission_id'), 'ai_evaluations', ['submission_id'], unique=True)
    op.create_table('evidence_items',
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['employee_submissions.id'], name=op.f('fk_evidence_items_submission_id_employee_submissions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_items'))
    )
    op.create_index(op.f('ix_evidence_items_source_type'), 'evidence_items', ['source_type'], unique=False)
    op.create_index(op.f('ix_evidence_items_submission_id'), 'evidence_items', ['submission_id'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=32), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('parse_status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['employee_submissions.id'], name=op.f('fk_uploaded_files_submission_id_employee_submissions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploaded_files')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_uploaded_files_storage_key'))
    )
    op.create_index(op.f('ix_uploaded_files_file_type'), 'uploaded_files', ['file_type'], unique=False)
    op.create_index(op.f('ix_uploaded_files_parse_status'), 'uploaded_files', ['parse_status'], unique=False)
    op.create_index(op.f('ix_uploaded_files_submission_id'), 'uploaded_files', ['submission_id'], unique=False)
    op.create_table('dimension_scores',
    sa.Column('evaluation_id', sa.String(length=36), nullable=False),
    sa.Column('dimension_code', sa.String(length=64), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=False),
    sa.Column('weighted_score', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['ai_evaluations.id'], name=op.f('fk_dimension_scores_evaluation_id_ai_evaluations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dimension_scores')),
    sa.UniqueConstraint('evaluation_id', 'dimension_code', name=op.f('uq_dimension_scores_evaluation_id'))
    )
    op.create_index(op.f('ix_dimension_scores_dimension_code'), 'dimension_scores', ['dimension_code'], unique=False)
    op.create_index(op.f('ix_dimension_scores_evaluation_id'), 'dimension_scores', ['evaluation_id'], unique=False)
    op.create_table('salary_recommendations',
    sa.Column('evaluation_id', sa.String(length=36), nullable=False),
    sa.Column('current_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('recommended_ratio', sa.Float(), nullable=False),
    sa.Column('recommended_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ai_multiplier', sa.Float(), nullable=False),
    sa.Column('certification_bonus', sa.Float(), nullable=False),
    sa.Column('final_adjustment_ratio', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['ai_evaluations.id'], name=op.f('fk_salary_recommendations_evaluation_id_ai_evaluations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_salary_recommendations'))
    )
    op.create_index(op.f('ix_salary_recommendations_evaluation_id'), 'salary_recommendations', ['evaluation_id'], unique=True)
    op.create_index(op.f('ix_salary_recommendations_status'), 'salary_recommendations', ['status'], unique=False)
    op.create_table('approval_records',
    sa.Column('recommendation_id', sa.String(length=36), nullable=False),
    sa.Column('approver_id', sa.String(length=36), nullable=False),
    sa.Column('step_name', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], name=op.f('fk_approval_records_approver_id_users')),
    sa.ForeignKeyConstraint(['recommendation_id'], ['salary_recommendations.id'], name=op.f('fk_approval_records_recommendation_id_salary_recommendations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_records')),
    sa.UniqueConstraint('recommendation_id', 'step_name', name=op.f('uq_approval_records_recommendation_id'))
    )
    op.create_index(op.f('ix_approval_records_approver_id'), 'approval_records', ['approver_id'], unique=False)
    op.create_index(op.f('ix_approval_records_decision'), 'approval_records', ['decision'], unique=False)
    op.create_index(op.f('ix_approval_records_recommendation_id'), 'approval_records', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_approval_records_step_name'), 'approval_records', ['step_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_records_step_name'), table_name='approval_records')
    op.drop_index(op.f('ix_approval_records_recommendation_id'), table_name='approval_records')
    op.drop_index(op.f('ix_approval_records_decision'), table_name='approval_records')
    op.drop_index(op.f('ix_approval_records_approver_id'), table_name='approval_records')
    op.drop_table('approval_records')
    op.drop_index(op.f('ix_salary_recommendations_status'), table_name='salary_recommendations')
    op.drop_index(op.f('ix_salary_recommendations_evaluation_id'), table_name='salary_recommendations')
    op.drop_table('salary_recommendations')
    op.drop_index(op.f('ix_dimension_scores_evaluation_id'), table_name='dimension_scores')
    op.drop_index(op.f('ix_dimension_scores_dimension_code'), table_name='dimension_scores')
    op.drop_table('dimension_scores')
    op.drop_index(op.f('ix_uploaded_files_submission_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_parse_status'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_file_type'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index(op.f('ix_evidence_items_submission_id'), table_name='evidence_items')
    op.drop_index(op.f('ix_evidence_items_source_type'), table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_index(op.f('ix_ai_evaluations_submission_id'), table_name='ai_evaluations')
    op.drop_index(op.f('ix_ai_evaluations_status'), table_name='ai_evaluations')
    op.drop_index(op.f('ix_ai_evaluations_ai_level'), table_name='ai_evaluations')
    op.drop_table('ai_evaluations')
    op.drop_index(op.f('ix_employee_submissions_status'), table_name='employee_submissions')
    op.drop_index(op.f('ix_employee_submissions_employee_id'), table_name='employee_submissions')
    op.drop_index(op.f('ix_employee_submissions_cycle_id'), table_name='employee_submissions')
    op.drop_table('employee_submissions')
    op.drop_index(op.f('ix_certifications_employee_id'), table_name='certifications')
    op.drop_index(op.f('ix_certifications_certification_stage'), table_name='certifications')
    op.drop_table('certifications')
    op.drop_index(op.f('ix_audit_logs_target_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_operator_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_import_jobs_status'), table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_import_type'), table_name='import_jobs')
    op.drop_table('import_jobs')
    op.drop_index(op.f('ix_evaluation_cycles_status'), table_name='evaluation_cycles')
    op.drop_index(op.f('ix_evaluation_cycles_name'), table_name='evaluation_cycles')
    op.drop_table('evaluation_cycles')
    op.drop_index(op.f('ix_employees_status'), table_name='employees')
    op.drop_index(op.f('ix_employees_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_manager_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_job_level'), table_name='employees')
    op.drop_index(op.f('ix_employees_job_family'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_no'), table_name='employees')
    op.drop_index(op.f('ix_employees_department'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
